---
title: "Weekly energy consumption"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(ggplot2)
library(plotly)
```

```{r}
#| label: import
#| include: false
rdg = readODS::read_ods(
  "data/energymonitor.ods"
  , sheet = "data"
) |> 
  subset(!is.na(rdg_gas)) |> 
  subset(select = c("date", "rdg_gas", "rdg_pow")) |> 
  as.data.table()

rdg[, date := as.POSIXct(date, format = "%m/%d/%Y")]
rdg[, season := year(date)]
rdg[, doy := yday(date)]

rdg[
  , offset_jul := yday(
    as.Date(
      paste(
        year(date)
        , "07"
        , "01"
        , sep = "-"
      )
    )
  )
]

rdg[
  , offset_dec := yday(
    as.Date(
      paste(
        year(date) - 1
        , "12"
        , "31"
        , sep = "-"
      )
    )
  )
]

rdg[, doy := doy - offset_jul + 1L]
rdg[doy <= 0, season := season - 1L]
rdg[doy <= 0, doy := doy + offset_dec]
rdg[, c("offset_jul", "offset_dec") := NULL]

rdg[, lab := format(date, format = "%Y-%b-%d")]
```

```{r}
#| label: preparation
#| include: false
cbm2kwh = 0.9355 * 11.517 

rdg[, use_pow_kwh := c(NA_real_, diff(rdg_pow))]
rdg[, use_gas := c(NA_real_, diff(rdg_gas))]
rdg[, use_gas_kwh := use_gas * cbm2kwh]

rdg[, c("rdg_pow", "rdg_gas", "use_gas") := NULL]

rdg[, cum_pow_kwh := use_pow_kwh]
rdg[, cum_gas_kwh := use_gas_kwh]
rdg[1L, cum_pow_kwh := 0]
rdg[1L, cum_gas_kwh := 0]
rdg[, cum_pow_kwh := cumsum(cum_pow_kwh), by = season]
rdg[, cum_gas_kwh := cumsum(cum_gas_kwh), by = season]

rdg = melt(
  rdg
  ,id.vars = c("season", "doy", "lab")
  , measure.vars = c("use_gas_kwh", "use_pow_kwh", "cum_gas_kwh", "cum_pow_kwh")
  , value.name = "use"
  , variable.name = "type"
  , na.rm = TRUE
)

rdg[, use := round(use, digits = 1L)]

setnames(
  rdg
  , old = c(
    "Season"
    , "Day"
    , "Date"
    , "Type"
    , "Consumption"
  )
)
```

::: panel-tabset
## Natural gas

```{r}
#| label: plt-gas
#| echo: false
#| fig-width: 10
#| fig-height: 8
ggplotly(
  ggplot(
    rdg[grep("gas", x = Type)]
    ,  mapping = aes(
      Day
      , y = Consumption
      , color = factor(Season)
      , group = Season
      , label = Date
    )
  ) + 
    geom_line() + 
    scale_x_continuous("Day of year") + 
    scale_y_continuous(
      ""
      , expand = expansion(c(0.25, 0.25))
    ) + 
    scale_color_manual(
      ""
      , values = c(
        "2022" = "gray80"
        , "2023" = "gray60"
        , "2024" = "gray20"
      )
    ) + 
    facet_wrap(
      "Type"
      , ncol = 1
      , scales = "free_y"
      , labeller = as_labeller(
        c(
          use_gas_kwh = "Natural gas [kWh]"
          , cum_gas_kwh = "Natural gas [kWh]"
        )
      )
    ) +
    theme_bw() + 
    theme(legend.position = "none")
  , tooltip = c("Consumption", "Date", "Season")
)
```

## Electricity

```{r}
#| label: plt-pow
#| echo: false
#| fig-width: 10
#| fig-height: 8
ggplotly(
  ggplot(
    rdg[grep("pow", x = Type)]
    ,  mapping = aes(
      Day
      , y = Consumption
      , color = factor(Season)
      , group = Season
      , label = Date
    )
  ) + 
    geom_line() + 
    scale_x_continuous("Day of year") + 
    scale_y_continuous(
      ""
      , expand = expansion(c(0.25, 0.25))
    ) + 
    scale_color_manual(
      ""
      , values = c(
        "2022" = "gray80"
        , "2023" = "gray60"
        , "2024" = "gray20"
      )
    ) + 
    facet_wrap(
      "Type"
      , ncol = 1
      , scales = "free_y"
      , labeller = as_labeller(
        c(
          use_pow_kwh = "Power [kWh]"
          , cum_pow_kwh = "Power [kWh]"
        )
      )
    ) +
    theme_bw() + 
    theme(legend.position = "none")
  , tooltip = c("Consumption", "Date", "Season")
)
```
:::
